spring.application.name=proyecto-catedra
spring.cloud.config.enabled=false
# Para H2 (base de datos en memoria)
spring.datasource.url=jdbc:h2:mem:catedrafinal
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
